# Generated by Django 5.2.3 on 2026-02-27 09:23

import django.db.models.deletion
import django.utils.timezone
import pos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=4, default=1, max_digits=6, null=True)),
                ('measurement_type', models.CharField(choices=[('each', 'each'), ('g', 'gram'), ('kg', 'kilogram'), ('ltr', 'litre')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='SalesReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True, max_length=200, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('issued', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('stock_inventory', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=50, null=True, validators=[pos.models.stock_inventory_validation])),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cats', to='pos.category')),
                ('outlet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='accounts.outlets')),
                ('sold_In', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measured_in', to='pos.measurement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8, validators=[pos.models.order_quantity_validation])),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('paid', models.BooleanField(default=False)),
                ('sub_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='pos.product')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_tenderd', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('payment_time', models.DateTimeField(blank=True, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('payment_for_receipt', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='pos.salesreceipt')),
            ],
        ),
        migrations.CreateModel(
            name='SalesReceiptOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_option', models.CharField(choices=[('TF', 'transfer'), ('CASH', 'cash'), ('CARD', 'card')], default='TF', max_length=4)),
                ('remarks', models.TextField(blank=True, max_length=200, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_salesreceipt', to='pos.order')),
                ('sales_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_receipt_order', to='pos.salesreceipt')),
            ],
        ),
        migrations.AddField(
            model_name='salesreceipt',
            name='orders',
            field=models.ManyToManyField(related_name='order_receipt', through='pos.SalesReceiptOrder', to='pos.order'),
        ),
    ]
