# Generated by Django 5.2.3 on 2026-04-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreceipt',
            name='issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
