# Generated by Django 5.2.3 on 2026-09-21 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_outlets_email_address'),
        ('pos', '0002_alter_payment_amount_tenderd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer_setup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_size', models.FloatField(max_length=5)),
                ('paper_height', models.FloatField(max_length=5)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.outlets')),
            ],
        ),
    ]
