# Generated by Django 5.2.3 on 2026-05-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_salesreceipt_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreceipt',
            name='hold',
            field=models.BooleanField(default=False),
        ),
    ]
