# Generated by Django 5.2.3 on 2026-09-21 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_outlets_email_address'),
        ('pos', '0003_printer_setup'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_size', models.PositiveSmallIntegerField(choices=[(58, '58 mm'), (80, '80 mm')], default=80)),
                ('outlet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='printer_setup', to='accounts.outlets')),
            ],
        ),
        migrations.DeleteModel(
            name='Printer_setup',
        ),
    ]
