# Generated by Django 5.2.3 on 2026-09-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_printersetup_delete_printer_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='measurement_type_at_sale',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='product_name_at_sale',
            field=models.CharField(default='lpg cooking gas', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='unit_cost_price',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='unit_selling_price',
            field=models.DecimalField(decimal_places=2, default=1200, max_digits=12),
            preserve_default=False,
        ),
    ]
