# Generated by Django 5.2.3 on 2026-05-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_salesreceipt_hold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreceipt',
            name='hold',
            field=models.BooleanField(default=True),
        ),
    ]
