# Generated by Django 5.2.3 on 2026-09-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_order_measurement_type_at_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='measurement_value_at_sale',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True),
        ),
    ]
