# Generated by Django 5.2.3 on 2026-05-15 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_outletstaff_failed_attempts_outletstaff_is_locked_and_more'),
        ('pos', '0005_alter_salesreceipt_hold'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='outlet',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='accounts.outlets'),
            preserve_default=False,
        ),
    ]
