# Generated by Django 5.2.3 on 2026-05-16 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_outletstaff_failed_attempts_outletstaff_is_locked_and_more'),
        ('pos', '0006_category_outlet'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='outlet',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='measured_types', to='accounts.outlets'),
            preserve_default=False,
        ),
    ]
