# Generated by Django 5.2.3 on 2026-05-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_measurement_outlet'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='salesreceiptorder',
            constraint=models.UniqueConstraint(fields=('order',), name='unique_order_per_receipt'),
        ),
    ]
