# Generated by Django 5.2.3 on 2026-06-24 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_remove_outletstaff_last_login_date_and_more'),
        ('pos', '0008_salesreceiptorder_unique_order_per_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(default='686da141-d963-460c-8a66-b67d95df3cf0', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.outletstaff'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
