# Generated by Django 5.2.3 on 2026-06-25 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_product_created_by_product_update_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
    ]
