# Generated by Django 5.2.3 on 2026-06-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0011_inventorylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylog',
            name='action',
            field=models.CharField(choices=[('add', 'add'), ('subtract', 'subtract')], max_length=20),
        ),
    ]
