# Generated by Django 5.2.3 on 2026-07-13 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_outletstafflogin_assigned'),
        ('pos', '0013_remove_inventorylog_performed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreceipt',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='staff_receipts', to='accounts.outletstaff'),
        ),
    ]
