# Generated by Django 5.2.3 on 2026-03-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outletstaff',
            name='description',
        ),
        migrations.AddField(
            model_name='outletstaff',
            name='phone_number',
            field=models.CharField(default='hdygdy', max_length=100),
        ),
    ]
