# Generated by Django 5.2.3 on 2026-09-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletstafflogin',
            name='assignment_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='outletstafflogin',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('outlet_staff',), name='only_one_active_staff_per_session'),
        ),
        migrations.AddConstraint(
            model_name='outletstafflogin',
            constraint=models.UniqueConstraint(condition=models.Q(('assigned', True)), fields=('outlet_staff',), name='only_one_asigned_staff_per_session'),
        ),
    ]
