# Generated by Django 5.2.3 on 2026-03-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_outletstaff_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outletstaff',
            name='Employee_id',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='outletstaff',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='outletstaff',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='outletstaff',
            name='phone_number',
            field=models.CharField(blank=True, default='hdygdy', max_length=100, null=True),
        ),
    ]
