# Generated by Django 5.2.3 on 2026-09-03 12:56

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_outletstafflogin_assignment_expires_at_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='outlets',
            constraint=models.UniqueConstraint(models.F('user'), django.db.models.functions.text.Lower('name'), name='Oulet_already_exist'),
        ),
    ]
