# Generated by Django 5.2.3 on 2026-03-05 10:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_outletstaff_employee_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outletstaff',
            name='id',
        ),
        migrations.AlterField(
            model_name='outletstaff',
            name='Employee_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
