# Generated by Django 5.2.3 on 2026-09-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_outlets_oulet_already_exist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlets',
            name='email_address',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
