# Generated by Django 5.2.3 on 2026-03-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_outletstaff_id_alter_outletstaff_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outletstafflogin',
            name='date',
        ),
        migrations.AddField(
            model_name='outletstafflogin',
            name='last_login_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
