# Generated by Django 5.2.3 on 2026-03-21 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_outletstafflogin_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='active_outlet_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='accounts.outletstaff'),
        ),
        migrations.AddField(
            model_name='outletstaff',
            name='last_login_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outletstaff',
            name='pin',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
