# Generated by Django 5.2.3 on 2026-03-21 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_active_outlet_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='active_outlet_staff',
        ),
        migrations.RemoveField(
            model_name='outletstaff',
            name='user',
        ),
    ]
