# Generated by Django 5.2.3 on 2026-03-21 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_customuser_active_outlet_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletstaff',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
