# Generated by Django 5.2.3 on 2026-03-21 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_outletstaff_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outletstaff',
            name='user',
        ),
    ]
