# Generated by Django 5.2.3 on 2026-03-21 15:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_outletstaff_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outletstafflogin',
            name='last_login_date',
        ),
        migrations.RemoveField(
            model_name='outletstafflogin',
            name='user',
        ),
        migrations.AddField(
            model_name='outletstafflogin',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='outletstafflogin',
            name='login_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='outletstafflogin',
            name='logout_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outletstafflogin',
            name='outlet',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='accounts.outlets'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='outletstafflogin',
            name='outlet_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.outletstaff'),
        ),
    ]
