# Generated by Django 5.2.3 on 2026-03-21 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_outletstafflogin_last_login_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outletstafflogin',
            name='outlet',
        ),
    ]
