# Generated by Django 5.2.3 on 2026-03-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_outletstafflogin_outlet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outletstafflogin',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='outletstafflogin',
            name='login_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
