# Generated by Django 5.2.3 on 2026-03-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_outletstafflogin_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outletstafflogin',
            name='login_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
