# Generated by Django 5.2.3 on 2026-03-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_outletstafflogin_login_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outletstaff',
            name='last_login_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
