# Generated by Django 5.2.3 on 2026-04-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_outletstaff_last_login_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlets',
            name='pin',
            field=models.CharField(default=6666, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='outletstaff',
            name='pin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
