# Generated by Django 5.2.3 on 2026-05-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_outletstaff_failed_attempts_outletstaff_is_locked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
