# Generated by Django 5.2.3 on 2026-06-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='pending_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
