# Generated by Django 5.2.3 on 2026-06-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlets',
            name='email_address',
            field=models.EmailField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='outletstaff',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
