# Generated by Django 5.2.3 on 2026-06-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_outlets_email_address_alter_outletstaff_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletstaff',
            name='username',
            field=models.CharField(default='phollarh', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='outletstaff',
            name='email',
            field=models.EmailField(default='fola@hmail.com', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
