# Generated by Django 5.2.3 on 2026-06-17 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_outletstaff_username_alter_outletstaff_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outletstafflogin',
            name='outlet_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.outletstaff'),
        ),
    ]
