# Generated by Django 5.2.3 on 2026-06-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_outletstafflogin_outlet_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outletstaff',
            name='last_login_date',
        ),
        migrations.AddField(
            model_name='outletstaff',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='686da141-d963-460c-8a66-b67d95df3cf0'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='outletstaff',
            name='pin',
            field=models.CharField(default=1111, max_length=255),
            preserve_default=False,
        ),
    ]
