# Generated by Django 5.2.3 on 2026-06-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_remove_outletstaff_last_login_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlets',
            name='supivisor_passcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
