# Generated by Django 5.2.3 on 2026-06-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_outletstaff_outlet_authorizationnonce'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizationnonce',
            name='object_details',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='authorizationnonce',
            name='object_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
