# Generated by Django 5.2.3 on 2026-07-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_authorizationnonce_object_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizationnonce',
            name='purpose',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
