# Generated by Django 5.2.3 on 2026-07-10 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_authorizationnonce_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletstafflogin',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outletstafflogin',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='outletstafflogin',
            name='outlet_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_login', to='accounts.outletstaff'),
        ),
    ]
