# Generated by Django 5.2.3 on 2026-07-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_outletstafflogin_assigned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletstafflogin',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
    ]
